#!/usr/bin/env bash
# print_assumptions.sh — capture `Print Assumptions` for each theorem
# named in the AUDIT_LIST below, writing one file per theorem under
# docs/assumptions/.
#
# The AUDIT_LIST is the source of truth. Each entry has the form
#
#   <output_stem>|<From … Require Import path>|<qualified theorem name>
#
# When a v3 module reaches CHECKED-EXACT and a Rocq theorem name is
# added to docs/FORMALIZATION_STATUS.md, add the corresponding entry
# here. CI diffs the generated files against what is committed under
# docs/assumptions/; a mismatch fails the job.
#
# Nothing here silently generates or hides axioms — the whole point is
# to keep the assumption footprint of every advertised checked
# theorem visible in the tree.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
OUT_DIR="${REPO_ROOT}/docs/assumptions"
mkdir -p "${OUT_DIR}"

# --------------------------------------------------------------------
# Audit list. Empty for now — no v3 theorem is yet CHECKED-EXACT.
# When adding entries, keep the format exactly:
#   stem|From … Require Import module|Module.theorem_name
# --------------------------------------------------------------------
AUDIT_LIST=()

if [ "${#AUDIT_LIST[@]}" -eq 0 ]; then
  echo "print_assumptions: audit list empty — nothing to check yet."
  echo "  add an entry when a v3 theorem reaches CHECKED-EXACT in"
  echo "  docs/FORMALIZATION_STATUS.md."
  exit 0
fi

TMPDIR="$(mktemp -d)"
trap 'rm -rf "${TMPDIR}"' EXIT

for entry in "${AUDIT_LIST[@]}"; do
  stem="${entry%%|*}"
  rest="${entry#*|}"
  reqline="${rest%%|*}"
  thmname="${rest#*|}"

  probe="${TMPDIR}/probe_${stem}.v"
  cat > "${probe}" <<EOF
${reqline}.
Print Assumptions ${thmname}.
EOF

  raw="${TMPDIR}/${stem}.raw"
  ( cd "${REPO_ROOT}/Coq" && coqc -R . UELAT "${probe}" ) 2>&1 > "${raw}"

  # Extract the block after "Axioms:" (or "Closed under the global context")
  out="${OUT_DIR}/${stem}.txt"
  {
    echo "# Print Assumptions ${thmname}"
    echo "# generated by .github/scripts/print_assumptions.sh"
    echo "# do not edit by hand — commit the generator's output"
    echo ""
    cat "${raw}"
  } > "${out}"

  echo "print_assumptions: wrote ${out}"
done
