#!/usr/bin/env bash
# print_assumptions.sh — capture `Print Assumptions` for each theorem
# named in the AUDIT_LIST below, writing one file per theorem under
# docs/assumptions/.
#
# The AUDIT_LIST is the source of truth. Each entry has the form
#
#   <output_stem>|<From … Require Import path>|<qualified theorem name>
#
# When a v3 module reaches CHECKED-EXACT and a Rocq theorem name is
# added to docs/FORMALIZATION_STATUS.md, add the corresponding entry
# here. CI diffs the generated files against what is committed under
# docs/assumptions/; a mismatch fails the job.
#
# Nothing here silently generates or hides axioms — the whole point is
# to keep the assumption footprint of every advertised checked
# theorem visible in the tree.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
OUT_DIR="${REPO_ROOT}/docs/assumptions"
mkdir -p "${OUT_DIR}"

# --------------------------------------------------------------------
# Audit list — one entry per Rocq theorem the correspondence table in
# docs/FORMALIZATION_STATUS.md advertises as CHECKED-EXACT or
# CHECKED-RESTRICTED. DEFINITION-EXACT rows do NOT go here (a
# definition has no meaningful Print Assumptions output).
#
# Format:
#   stem|From … Require Import <files>|<qualified theorem name>
# --------------------------------------------------------------------
AUDIT_LIST=(
  "prop_3_3_lower_bound|From UELAT.V3 Require Import Presentation Evidence MetricReflection|V3_MetricReflection.prop_3_3_lower_bound"
  "lawvere_bounds_analytic|From UELAT.V3 Require Import Presentation Evidence MetricReflection|V3_MetricReflection.lawvere_bounds_analytic"
  "extensional_collapse|From UELAT.V3 Require Import Presentation Evidence MetricReflection|V3_MetricReflection.extensional_collapse"
  "principal_evidence_dense|From UELAT.V3 Require Import Presentation Evidence MetricReflection EffectiveCompleteness|V3_EffectiveCompleteness.principal_evidence_dense"
  "principal_evidence_dense_analytic|From UELAT.V3 Require Import Presentation Evidence MetricReflection EffectiveCompleteness|V3_EffectiveCompleteness.principal_evidence_dense_analytic"
)

if [ "${#AUDIT_LIST[@]}" -eq 0 ]; then
  echo "print_assumptions: audit list empty — nothing to check yet."
  echo "  add an entry when a v3 theorem reaches CHECKED-EXACT in"
  echo "  docs/FORMALIZATION_STATUS.md."
  exit 0
fi

TMPDIR="$(mktemp -d)"
trap 'rm -rf "${TMPDIR}"' EXIT

for entry in "${AUDIT_LIST[@]}"; do
  stem="${entry%%|*}"
  rest="${entry#*|}"
  reqline="${rest%%|*}"
  thmname="${rest#*|}"

  probe="${TMPDIR}/probe_${stem}.v"
  cat > "${probe}" <<EOF
${reqline}.
Print Assumptions ${thmname}.
EOF

  raw="${TMPDIR}/${stem}.raw"
  # Redirect stdout AND stderr to the raw file — coqc writes
  # Print Assumptions output on stdout, but errors on stderr, and we
  # want both captured.
  #
  # NO `|| true` here. A coqc failure means either the theorem name is
  # wrong, the module does not compile, or the Require path is broken —
  # in every one of those cases the audit has NOT established anything
  # and must fail loudly rather than committing an error message as if
  # it were an assumption report. `set -e` at the top propagates it.
  if ! ( cd "${REPO_ROOT}/Coq" && coqc -R . UELAT "${probe}" ) > "${raw}" 2>&1; then
    echo "::error::print_assumptions: coqc failed for ${thmname}" >&2
    echo "--- probe file ---" >&2
    cat "${probe}" >&2
    echo "--- coqc output ---" >&2
    cat "${raw}" >&2
    exit 1
  fi

  # Keep ONLY the Print Assumptions verdict block — either the single
  # "Closed under the global context" line, or everything from the
  # "Axioms:" header onward. Everything else is discarded.
  #
  # This matters for reproducibility: coqc also emits deprecation and
  # notation warnings that quote the probe's path, and the probe lives
  # in a fresh `mktemp -d` on every run. Committing those would make
  # the file differ run-to-run and trip the drift check on every CI
  # build, which would train reviewers to ignore a real drift signal.
  if grep -q '^Closed under the global context' "${raw}"; then
    verdict="$(grep '^Closed under the global context' "${raw}")"
  else
    verdict="$(sed -n '/^Axioms:/,$p' "${raw}")"
  fi

  if [ -z "${verdict}" ]; then
    echo "::error::print_assumptions: no verdict block found for ${thmname}" >&2
    echo "--- coqc output ---" >&2
    cat "${raw}" >&2
    exit 1
  fi

  out="${OUT_DIR}/${stem}.txt"
  {
    echo "# Print Assumptions ${thmname}"
    echo "# generated by .github/scripts/print_assumptions.sh -- do not edit by hand"
    echo "#"
    echo "# Only the Print Assumptions verdict is retained; coqc warnings are"
    echo "# dropped because they quote a per-run temporary path."
    echo ""
    echo "${verdict}"
  } > "${out}"

  # Echo into the build log as well, so the assumption footprint is
  # reviewable directly from a CI run without downloading the artifact.
  echo "===== BEGIN ${stem}.txt ====="
  cat "${out}"
  echo "===== END ${stem}.txt ====="
done
